---

- name: Copy experiments scripts
  copy: "src=../../../experiments/ dest=/etc/experiments/"

- name: Copy startup scripts
  copy: "src=. dest=/usr/local/sbin mode=0755"

- name: Create loggers group
  group: name=loggers

- name: Add root to loggers group
  user: name=root groups=loggers append=yes

- name: Create log folders
  file: "path={{ item }} state=directory group=loggers mode=2775"
  with_items:
    - /var/log/nightking
    - /var/log/nightking/cache
    - /var/log/nightking/flag

- name: Set noautorun flag
  when: NOAUTORUN is defined and NOAUTORUN != ""
  file: path=/var/log/nightking/flag/noautorun state=touch

- name: Enable startup script at startup
  cron: name=startupjob job=/usr/local/sbin/startup.bash special_time=reboot

- name: Add library.bash light to bashrc
  copy:
    dest: /etc/profile.d/library.sh
    mode: 0755
    content: |
      source /usr/local/sbin/library.bash light

- name: Create .ssh for root
  file: path=/root/.ssh state=directory mode=0700

- name: Add ssh config to root
  copy:
    dest: /root/.ssh/config
    mode: 0600
    content: |
      Host *
        User ec2-user
        StrictHostKeyChecking no
        IdentityFile /var/log/nightking/pool.key
        ServerAliveInterval 120
        LogLevel ERROR
