---

- name: Disable journald rate-limiting
  lineinfile: "dest=/etc/systemd/journald.conf regexp={{item.regexp}} line='{{item.line}}'"
  with_items:
  - { regexp: "^#RateLimitInterval", line: "RateLimitInterval=0s" }
  - { regexp: "^#RateLimitBurst", line: "RateLimitBurst=0" }
  - { regexp: "^#SystemMaxFileSize", line: "SystemMaxFileSize=100M" }
  - { regexp: "^#SystemMaxUse", line: "SystemMaxUse=500M" }
  - { regexp: "^#SystemMaxFiles", line: "SystemMaxFiles=10" }

- name: Change logrotate to daily
  lineinfile: "dest=/etc/logrotate.conf regexp={{item.regexp}} line='{{item.line}}'"
  with_items:
  - { regexp: "^weekly", line: "daily" }
  - { regexp: "^#compress", line: "compress" }

- name: Create journal directory for permanent logs
  file: path=/var/log/journal state=directory

- name: Set journal folder with systemd-tmpfiles
  command: "systemd-tmpfiles --create --prefix /var/log/journal"
