---

- hosts: all
  any_errors_fatal: true
  gather_facts: no
  become: yes
  become_user: root
  roles:
    - yum
    - { role: debug, when: DEBUG is defined and (DEBUG | bool) }
    - journald
    - openfiles
    - terraform
    - terraform-templates
    - tendermint
    - monitoring
    - experiments
    - scripts
    #tm-load-test now depends on the scripts role, because scripts introduces a group that tm-load-test need to be part of.
    - tm-load-test
