#!/usr/bin/env bash
set -euo pipefail

FAST=1 source /usr/local/sbin/library.bash

stop-tm-load-test() {
    PIDS="$(pidof tm-load-test || echo "")"
    if [ -z "${PIDS}" ]; then
        echo "No pids found for tm-load-test."
    else
        echo "Killing tm-load-test PID(s): ${PIDS}"
        kill "${PIDS}"
    fi
}

stop-tendermint() {
    systemctl stop tendermint || true
}

case "${ROLE}" in
  "nightking")
    stop-tm-load-test
    pssh -i -p "${MAX_PARALLEL_SSH}" -H "$(get-all-whitewalkers-ip)" "sudo /usr/local/sbin/stopxp"
    test -z "${FULL:-}" || stop-tendermint
    test -z "${FULL:-}" || pssh -i -p "${MAX_PARALLEL_SSH}" -H "$(get-all-starks-ip)" "sudo FULL=1 /usr/local/sbin/stopxp"
    ;;
  "whitewalker")
    stop-tm-load-test
    ;;
  "stark")
    test -z "${FULL:-}" || stop-tendermint
    ;;
  *)
    echo "Cannot understand ROLE=${ROLE}" > "${LOG_DIR}/startup-error"
    ;;
esac
