---

- name: Download terraform
  get_url:
    url: https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
    dest: /tmp/terraform.zip
    checksum: sha256:5925cd4d81e7d8f42a0054df2aafd66e2ab7408dbed2bd748f0022cfe592f8d2

- name: Unpack terraform
  unarchive:
    src: /tmp/terraform.zip
    dest: /usr/bin
    remote_src: yes
    owner: root
    group: root
    mode: 0755

- name: Cleanup terraform post-install
  file: path=/tmp/terraform.zip state=absent
